default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        exclude: |
          (?x)^(
            examples/.*|
            robin_output/.*
            )$
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black-jupyter
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.5.3
    hooks:
      - id: prettier
        exclude: robin_output
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.2
    hooks:
      - id: toml-sort-fix
  - repo: https://github.com/crate-ci/typos
    rev: v1.30.3
    hooks:
      - id: typos
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: check-mailmap
  - repo: https://github.com/henryiii/validate-pyproject-schema-store
    rev: 2025.03.24
    hooks:
      - id: validate-pyproject
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.10
    hooks:
      - id: uv-lock
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.19.1
    hooks:
      - id: blacken-docs
        exclude: \.md$ # The generated markdown files are being blackened by jupytext
  - repo: https://github.com/srstevenson/nb-clean
    rev: 4.0.1
    hooks:
      - id: nb-clean
        args: [--preserve-cell-outputs, --remove-empty-cells]
  - repo: https://github.com/mwouts/jupytext
    rev: v1.17.0rc2
    hooks:
      - id: jupytext
        args: [--to, md, --pipe, black]
        additional_dependencies: [black]
        files: ^docs/.*\.ipynb$
  - repo: https://github.com/jsh9/markdown-toc-creator
    rev: 0.0.10
    hooks:
      - id: markdown-toc-creator
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: [--pretty, --ignore-missing-imports]
        additional_dependencies:
          - anthropic
          - fhaviary
          - fhlmi
          - openai>=1 # Match pyproject.toml
          - pandas-stubs
          - pydantic>=2 # Match pyproject.toml
          - types-aiofiles
          - types-PyYAML
          - types-setuptools
          - types-tqdm
